# Generated by Django 3.0.8 on 2021-01-19 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210117_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
